### ISSUE TITLE
Newline

### ISSUE THREAD

**Issue by olemed** [websjef-delta/tmp-deltahouse#9]
Fikse slik at man kan få nytt avsnitt i en tekst

**Comment by websjef-delta** [comment]
Skal finne ut av det for dere boomers

**Comment by websjef-delta** [comment]
Vent faen, innså hva problemet er, og at jeg allerede jobber med saken. Bare fortsett å bruke rich text og godta at det kommer til å stå '//' frem til jeg fikser det.
